// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVMzKXD-Tutu66rC8I35tTSmA2Ge7T2aU',
    appId: '1:914719638637:web:a038d5975e74d3b8c0eb64',
    messagingSenderId: '914719638637',
    projectId: 'manacareer-2d2cc',
    authDomain: 'manacareer-2d2cc.firebaseapp.com',
    storageBucket: 'manacareer-2d2cc.firebasestorage.app',
    measurementId: 'G-YBL262NQHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGi4if5y10sEGgCA9Xrd2f-9esdoa56t8',
    appId: '1:914719638637:android:ba29b5a7de5a260ec0eb64',
    messagingSenderId: '914719638637',
    projectId: 'manacareer-2d2cc',
    storageBucket: 'manacareer-2d2cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Jv5XGjtJTsy4W3rylRuhjpC4ezgikks',
    appId: '1:914719638637:ios:233f043dcc18bf1ec0eb64',
    messagingSenderId: '914719638637',
    projectId: 'manacareer-2d2cc',
    storageBucket: 'manacareer-2d2cc.firebasestorage.app',
    iosBundleId: 'com.example.manacareerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Jv5XGjtJTsy4W3rylRuhjpC4ezgikks',
    appId: '1:914719638637:ios:233f043dcc18bf1ec0eb64',
    messagingSenderId: '914719638637',
    projectId: 'manacareer-2d2cc',
    storageBucket: 'manacareer-2d2cc.firebasestorage.app',
    iosBundleId: 'com.example.manacareerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVMzKXD-Tutu66rC8I35tTSmA2Ge7T2aU',
    appId: '1:914719638637:web:8a0e63df95c04976c0eb64',
    messagingSenderId: '914719638637',
    projectId: 'manacareer-2d2cc',
    authDomain: 'manacareer-2d2cc.firebaseapp.com',
    storageBucket: 'manacareer-2d2cc.firebasestorage.app',
    measurementId: 'G-F69ZE4FJSG',
  );
}
